// Pulls PDF download links out of embed blocks generated by either the WP
// migration script or the admin's own PdfInserter — both use the same
// `<a href="...">Download PDF</a>` pattern, so this covers both sources.
export function extractPdfLinks(html) {
  if (!html) return [];
  const matches = [...html.matchAll(/<a href="([^"]+)"[^>]*>Download PDF<\/a>/g)];
  return matches.map((m) => m[1]);
}
